UI from main
FlutterTeamOne/flutter_chat_app pull request #23
Opened 2022-12-15 13:05 UTC by bukhanovskayamarina22

2022-12-15 13:28 UTC, SharovIvanY requested changes
Вынести main из файла lib/modules/client/users_client.dart
lib/ui/widgets/authentication page/widgets/new_user_widget.dart - Сделать ссылку мультистрокой ('''те
кс
т''')

2022-12-16 07:30 UTC, faradzhalelov approved these changes

2022-12-16 07:51 UTC, SharovIvanY requested changes
Добавить ReadUsersEvent

2022-12-16 07:52 UTC, closed without merging

2022-12-16 07:52 UTC, SharovIvanY commented
Не доделано