Validation to create user
FlutterTeamOne/flutter_chat_app pull request #76
Opened 2023-01-10 23:47 UTC by x4dead

add email_validator in pubspec.yaml, made form_widget, add obscureText for password. Add validation for: name form, email form, password form.

2023-01-11 06:32 UTC, SharovIvanY reviewed
Добавлен единый виджет для полей ввода.
Добавлен валидатор на имя (Не менее 3 символов, Состоит из букв)

2023-01-11 06:32 UTC, SharovIvanY requested changes
Добавлен валидатор на email (Не уверен в правильности RegExp)
https://ru.stackoverflow.com/questions/571772/%D0%A0%D0%B5%D0%B3%D1%83%D0%BB%D1%8F%D1%80%D0%BD%D0%BE%D0%B5-%D0%B2%D1%8B%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B4%D0%BB%D1%8F-%D0%BF%D0%BE%D0%BB%D0%BD%D0%BE%D0%B9-%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B8-email

2023-01-11 06:35 UTC, SharovIvanY requested changes
Добавлен валидатор для пароля (Не менее 6 символов)
Пакет emailValidatod?
Простой (но правильный) класс Dart для проверки адресов электронной почты без использования RegEx. Зачем тогда там RegExp?

2023-01-11 14:45 UTC, forswow submitted a review, later dismissed

2023-01-12 06:28 UTC, slavlen approved these changes
Проверил

2023-01-12 12:55 UTC, x4dead commented
сделали bukhanovskayamarina22 и x4dead

2023-01-12 14:44 UTC, slavlen approved these changes
Вроде хорошо работает

2023-01-13 15:25 UTC, SharovIvanY commented
Смержено в bugger, можно закрывать пулл

2023-01-13 17:15 UTC, closed without merging