Authentication bug
FlutterTeamOne/flutter_chat_app pull request #80
Opened 2023-01-12 16:30 UTC by x4dead

remade listview to gridview,add two text(decor), change user_card, add simple method(adaptation),  change user_card: add overlayColor for  image, add adaptation for text style.

2023-01-12 18:49 UTC, forswow approved these changes

2023-01-12 18:53 UTC, forswow commented
нужно добавить список в wrap, чтоб центровка по центру была

2023-01-12 18:54 UTC, SharovIvanY requested changes
Не нравится стиль начального экрана.
Сделать бы выравнивание по центру.
Картинки плывут, скорее всего с качеством проблемы, надо бы исправить....Артур советует поправить BoxFit
Кнопка добавить юзера не приметна...

2023-01-14 15:37 UTC, SharovIvanY commented
Смержено в bugger

2023-01-14 15:37 UTC, closed without merging